name: quitanda_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.4.0
  badges: ^3.1.1
  intl: ^0.17.0
  add_to_cart_animation: ^0.0.7
  fluttertoast: ^8.2.1
  shimmer: ^2.0.0
  get: ^4.6.5
  dio: ^5.1.2
  json_annotation: ^4.4.1
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  flutter_secure_storage: ^5.0.2
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.6
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/fruits/
    - assets/app_images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_images/app_icon.png"
  remove_alpha_ios: true
